version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      android-build:
        patterns:
          - "com.android.*"
          - "org.jetbrains.kotlin*"
          - "gradle-wrapper"
        update-types:
          - "major"
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
