name: Tests and Dependabot PR Handling

on:
  pull_request:
    branches:
      - master
      - main
permissions:
  contents: write
  pull-requests: write

jobs:
  # Verifies the boilerplate can be built
  test-for-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
  
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      
      - name: prebuild Dependencies
        run: |
          ./gradlew dependencies

      - name: Build Debug APK
        run: |
          ./gradlew assembleDebug

  auto-merge-dependabot:
    needs:
      - test-for-build
    runs-on: ubuntu-20.04
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}